# Install script for directory: /home/markus/Projekte/s25rttr-android/app/jni/boost

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/filesystem/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/iostreams/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/program_options/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/test/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/nowide/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/assert/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/any/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/algorithm/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/config/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/bind/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/array/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/container_hash/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/core/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/throw_exception/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/concept_check/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/detail/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/type_index/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/exception/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/static_assert/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/describe/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/preprocessor/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/io/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/function/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/type_traits/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/smart_ptr/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/mp11/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/iterator/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/integer/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/tuple/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/move/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/mpl/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/lexical_cast/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/function_types/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/container/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/predef/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/fusion/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/range/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/numeric_conversion/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/tokenizer/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/random/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/system/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/variant2/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/dynamic_bitset/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/conversion/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/typeof/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/intrusive/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/utility/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/regex/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/optional/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/scope/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/atomic/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/unordered/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/functional/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/winapi/cmake_install.cmake")
  include("/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/align/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/home/markus/Projekte/s25rttr-android/app/jni/boost/temp/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
