name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Update submodules
      run: git pull --recurse-submodules

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install openjdk-17-jdk wget curl gradle cmake unzip

    - name: Install Android NDK r27 & r23
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r23-linux.zip -o ndk-r23
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -o ndk-r27
        unzip ndk-r23
        unzip ndk-r27
        mkdir -p $HOME/Android/Sdk/ndk
        mv -r android-ndk-r23 $HOME/Android/Sdk/ndk/r23
        mv -r android-ndk-r27c $HOME/Android/Sdk/ndk/r27
    
    - name: Run gradlew to install sdk
      run: android-project/build.sh assembleDebug

    - name: Build dependencies
      run: NDK23="~/Android/ndk/r23" NDK27="~/Android/ndk/27" ./build_dependencies.sh

    - name: Patch s25client
      run: ./patches.sh --apply-patch

    - name: Moving into android project
      run: cd android-project

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
